CREATE TABLE Bar(
Id		INT		PRIMARY KEY,
Name		VARCHAR(20)	NOT NULL,
StreetName	VARCHAR(20)	NOT NULL,
StreetNumber	SMALLINT	NOT NULL,
City		VARCHAR(20)	NOT NULL,
State		VARCHAR(2)	NOT NULL,
ZipCode		VARCHAR(5)	NOT NULL,
Location	POINT		NOT NULL
);

CREATE TABLE Account(
Id		VARCHAR(128)	PRIMARY KEY,
FirstName	VARCHAR(20)	NOT NULL,
LastName	VARCHAR(20)	NOT NULL,
BarId		INT,
CONSTRAINT fk_bar FOREIGN KEY(BarId) REFERENCES Bar(Id)
);
